name: Starter (Reusable)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  call-reusable-starter:
    permissions:
      checks: write
    uses: tmx-kenmotsu/.github/.github/workflows/reusable-starter.yml@main
    with:
      buildCommand: ./build.sh
      staticAnalysisCommand: ./static-analysis.sh
      unitTestCommand: ./unit-test.sh
    secrets: inherit
