name: Starter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up JDK 17
      uses: actions/setup-java@v4.7.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: ./build.sh
    - name: Upload Build Artifacts
      if: success()
      uses: actions/upload-artifact@v4.6.0
      with:
        name: build-artifacts
        path: '**/*.jar'
    # - uses: tlolkema/simple-teams-message@1.1.0
    #   if: always()
    #   with:
    #     message_title: "title"
    #     message_description: "description"
    #     webhook: ${{ secrets.TEAMS_WEBHOOK }}

  static-analysis:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      checks: write
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up JDK 17
      uses: actions/setup-java@v4.7.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Static Analysis with SpotBugs
      run: ./static-analysis.sh
    - name: Publish Test Report
      if: always()
      uses: jwgmeligmeyling/spotbugs-github-action@v1.2
      with:
        path: '**/spotbugsXml.xml'
    - name: Upload Static Analysis Reports
      if: always()
      uses: actions/upload-artifact@v4.6.0
      with:
        name: sa-reports
        path: '**/spotbugsXml.xml'

  unit-test:
    needs: static-analysis
    runs-on: ubuntu-latest
    permissions:
      checks: write
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up JDK 17
      uses: actions/setup-java@v4.7.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Unit Test with JUnit
      run: ./unit-test.sh
    - name: Publish Test Reports
      if: always()
      uses: mikepenz/action-junit-report@v5.2.0
      with:
        report_paths: '**/TEST-*.xml'
    - name: Upload Unit Test Reports
      if: always()
      uses: actions/upload-artifact@v4.6.0
      with:
        name: ut-reports
        path: '**/TEST-*.xml'
